### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by carlthome** [sigsep/sigsep-mus-eval#16]
```python
import numpy as np
from museval.metrics import bss_eval

references = np.random.normal(size=(3, 44100, 2))
estimates = np.random.normal(size=(3, 44100, 2))

bss_eval(references, estimates)
```
results in `TypeError: slice indices must be integers or None or have an __index__ method`. Am I doing something wrong? 😕 

```sh
python --version
Python 3.6.4 :: Anaconda, Inc.

pip show museval
Version: 0.2.0
```

**Comment by faroit** [comment]
The new defaults windows length is 2s = 88200 samples on 44.1Khz.

See parameters [here](https://sigsep.github.io/sigsep-mus-eval/museval.metrics.html#museval.metrics.bss_eval)

Yes, I should have included a check + proper error handling ;-)

**Comment by carlthome** [comment]
Aha, my bad! Thanks.

**Comment by enisnazif** [comment]
Hi, i'm also receiving this error. Could you please possibly explain what you meant by your answer to the question? @faroit

**Comment by carlthome** [comment]
Your audio signal is probably shorter than the window length so not even a single frame is produced.

**Comment by faroit** [comment]
Okay, but I really need to raise a more specific warning here. So I'll leave this open for now.

**Comment by f90** [comment]
Somehow this problem still exists in the current master version available via pip (0.2.1 version), so you can't use bss_eval with default arguments - is this fix by @hagenw not merged into master yet, @faroit ? Thanks!!

**Comment by faroit** [comment]
Nope, sorry. It's currently in #56 which I want to merge and finally release within the next couple of days.

**Comment by faroit** [comment]
#56 is merged into the master now. pypi releases will follow soon. Sorry for the delay
