### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by bmcfee** [sigsep/sigsep-mus-eval#43]
Hey sigsep pals!  What's the preferred way to cite this software package (as distinct from sisec more generally).  Is there any chance of getting a DOI (say by zenodo) for this package to encourage proper citation?

**Comment by faroit** [comment]
sure. Forgot to do that back then. made a zenodo release and updated readme via b5f3c76

**Comment by bmcfee** [comment]
Thanks, that was fast!
