### ISSUE TITLE
Only supporting old musdb?

### ISSUE THREAD

**Issue by keunwoochoi** [sigsep/sigsep-mus-eval#62]
Hi, I was installing `museval` and had this error message.
```
ERROR: museval 0.2.1 has requirement musdb==0.2.3, but you'll have musdb 0.3.1 which is incompatible.
```

Am I supposed to use the old `musdb` only?

**Comment by keunwoochoi** [comment]
Hmm, but I also could import both museval and musdb. Anyway, it was a little confusing for me :)

**Comment by faroit** [comment]
Yes, #56

**Comment by keunwoochoi** [comment]
Cool, thanks!

**Comment by faroit** [comment]
@keunwoochoi `0.3.0b1` is released. feedback is welcome ;-)

**Comment by faroit** [comment]
also pinging @hagenw @f90 @TE-StefanUhlich @ethman @pseeth
