### ISSUE TITLE
Linear Mix ?

### ISSUE THREAD

**Issue by HusseinYoussef** [sigsep/sigsep-mus-eval#71]
is working on the linear mix that is computed by summing the sources will yield the same results as working on the non-linear mix ?

**Comment by faroit** [comment]
@HusseinYoussef I think this issue is out of scope for open-unmix and rather concerns museval. So i moved it here.

**Comment by HusseinYoussef** [comment]
@faroit  Sorry i meant that validation the non-linear mixes are used for MUSDB18. will it be so different or wrong to use the linear mixes in validation?

**Comment by faroit** [comment]
not at all - of course this would be even more "correct".  its just that I would not recommend this for publishing a paper as this would get away from the default evaluation

**Comment by HusseinYoussef** [comment]
ok thanks alot.
