### ISSUE TITLE
Futurewarning: `pandas.io.json.json_normalize` is deprecated

### ISSUE THREAD

**Issue by aliutkus** [sigsep/sigsep-mus-eval#72]
Getting this
> museval/aggregate.py:409: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

I think it's fixed in the master here, but not in the pip package

**Comment by faroit** [comment]
Yes. Will issue a new version soon.

**Comment by faroit** [comment]
pushed `0.3.1` to pypi. sorry for the delay
