### ISSUE TITLE
[FEATURE] Add `museval` version to JSON file

### ISSUE THREAD

**Issue by TE-StefanUhlich** [sigsep/sigsep-mus-eval#8]
I think it would be good to add the `museval` version to the produced JSON files:

```javascript
{
    "museval": "0.2.0"
    "targets": [
      ...
```

By this, we can keep track of which version was used for the evaluation, which is interesting if we change/update `museval`.

**Comment by faroit** [comment]
good point, yes. I will change that and possibly update the [submissions](https://github.com/sigsep/sigsep-mus-2018/tree/master/submissions)

**Comment by faroit** [comment]
Also add the ffmpeg version that was used to decode the files if loaded from stems

**Comment by faroit** [comment]
this feature has been added in #56
