### ISSUE TITLE
IndexError when evaluate by museval

### ISSUE THREAD

**Issue by aystiro** [sigsep/sigsep-mus-eval#85]
I run this code and get index error, both folders have 50 musdb18 test songs and have same names. 
`museval.eval_dir("./predict/target/", "./predict/pred/", output_dir=None, mode='v4', win=1.0, hop=1.0)`

```
C:\Users\emiry\AppData\Local\Programs\Python\Python39\lib\site-packages\museval\__init__.py:400: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  estimates = np.array(estimates)
C:\Users\emiry\AppData\Local\Programs\Python\Python39\lib\site-packages\museval\__init__.py:401: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  references = np.array(references)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\emiry\AppData\Local\Programs\Python\Python39\lib\site-packages\museval\__init__.py", line 115, in eval_dir
    SDR, ISR, SIR, SAR = evaluate(
  File "C:\Users\emiry\AppData\Local\Programs\Python\Python39\lib\site-packages\museval\__init__.py", line 404, in evaluate
    references, estimates = pad_or_truncate(references, estimates)
  File "C:\Users\emiry\AppData\Local\Programs\Python\Python39\lib\site-packages\museval\__init__.py", line 348, in pad_or_truncate
    if est_shape[1] != ref_shape[1]:
IndexError: tuple index out of range
```

**Comment by faroit** [comment]
Can you check the duration and number of channels? Maybe your predictions are mono instead of stereo?

**Comment by aystiro** [comment]
> Can you check the duration and number of channels? Maybe your predictions are mono instead of stereo?
Oh, yes they are mono. Both test and predictions are mono. I'm sure about their durations, so I thought if I delete the line that calls pad_or_truncate function it would work, but it did not. 

So, I guess you only support stereo audio, then I must use stereo. 

Thanks.

**Comment by aystiro** [comment]
Although that converting to stereo from mono, I still have same issue. 

Checking stereo like that:
```
from scipy.io import wavfile

_, ref = wavfile.read("./target.wav")
_, est = wavfile.read("./pred.wav")
print(ref.shape)
print(est.shape)
```
Output:
```
(3329280, 2)
(3329280, 2)
```

These two sample sound files are attached.
[wav-files.zip](https://github.com/sigsep/sigsep-mus-eval/files/7909316/wav-files.zip)

**Comment by faroit** [comment]
Inside of museval the reference and estimate have 3 dimensions since it stacks all estimates for one track. 

You can't run museval with a single source estimate. You need at least two sources (e.g vocals and accompaniment). Did you made sure this is the case?

**Comment by aystiro** [comment]
No, I trained a model for just single source which is vocal. So, I tried to evaluate that. Is there a way for that?

**Comment by aliutkus** [comment]
Could you define some accompaniment source as 'mix-vocals' ?
Best

**Comment by faroit** [comment]
@aystiro can this be closed?
