### ISSUE TITLE
Pypi package update

### ISSUE THREAD

**Issue by d-dawg78** [sigsep/sigsep-mus-eval#90]
Hello 👋 

It seems like the [issue](https://github.com/sigsep/sigsep-mus-eval/pull/88) related to [numpy](https://pypi.org/project/numpy/)'s `np.float` was solved recently. Congrats!

However, the new wheels have not been updated in [pypi](https://pypi.org/project/musdb/#files) which poses a problem when installing the updated package (the issue remains in version 4.0.0).

Is there any way this could be updated? Maybe in version 4.0.1?

Thanks in advance!

**Comment by faroit** [comment]
new release `4.1.0` is uploaded to pypi, sorry for the delay
